name: Build & Verify

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: IDEA ${{ matrix.idea }} & JDK ${{ matrix.jdk }}
    strategy:
      fail-fast: false
      matrix:
        idea: [ '2024.3', '2025.1', '2025.2' ] # 'LATEST-EAP-SNAPSHOT'
        jdk: [ '21' ]
        #os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v5
    - name: Set up JDK ${{ matrix.jdk }}
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{ matrix.jdk }}
        cache: gradle

    - name: build & check
      env:
        ORG_GRADLE_PROJECT_ideaVersion: ${{ matrix.idea }}
      run: ./gradlew build check

    - name: Build Plugin
      env:
        ORG_GRADLE_PROJECT_ideaVersion: ${{ matrix.idea }}
      run: ./gradlew buildPlugin

    - name: Verify Plugin
      env:
          ORG_GRADLE_PROJECT_ideaVersion: ${{ matrix.idea }}
      run: ./gradlew verifyPlugin
